### ISSUE TITLE
push notifications not working on android

### ISSUE THREAD

**Issue by fidoboy** [AppGyver/PushNotifications#7] opened 2015-01-16 13:27 UTC
When app is in foreground, notifications doesn't work

**Comment by fidoboy** [comment] 2015-01-20 15:37
hello?

**Comment by fidoboy** [comment] 2015-01-20 18:05
The messageInForegroundHandler event is not being triggered on android. Same code working fine on iOS

**Comment by pre** [comment] 2015-01-21 08:35
Please post a code reproduction. I cannot reproduce your issue, in our tests everything is working fine.

You could even try with the Steroids.js testapp: https://github.com/AppGyver/steroids-js/blob/next/testApp/app/controllers/plugin.coffee#L33 (just change the api id, it's hardcoded in the controller).

**Comment by harsaharsa** [comment] 2015-01-21 09:29
Note that if you register with an incorrect API ID, you need to unregister() before calling register again.

**Comment by pre** [comment] 2015-01-21 10:52
That's true, the one (undocumented?) quirk is that you must either manually `unregister()` (or reinstall the app) if your application id has registered even once with an incorrect API key. Could this be the case, @fidoboy ?

**Comment by fidoboy** [comment] 2015-01-21 11:49
I believe that it's not the case, cause if i put the pp in background, the notification comes to device and i can see it on android notification center. Sometimes also, when going from background to foreground, the notification is displayed on my app and the foreground event in my app is being triggered

**Comment by fidoboy** [comment] 2015-01-21 11:51
Exact same code is working fine for iOS in my app... I'm using initial view, that it's always loaded, to manage the push notification events

**Comment by pre** [comment] 2015-01-21 12:00
Can you get it working with the Steroids.js testapp? We currently have only a *working* example, we do not have a code reproduction for the problem.

**Comment by fidoboy** [comment] 2015-01-21 12:04
I've not tried it with testapp yet, can you provide a link?

**Comment by pre** [comment] 2015-01-21 12:14
The link is in one of my comments above.

**Comment by fidoboy** [comment] 2015-01-21 12:59
Oops!! I must be blind :) Many thanks Petrus, i'll try it right now. If it works, i think that it could be easy to me to locate the source of the problem on my app, comparing with that code.

**Comment by fidoboy** [comment] 2015-01-21 15:11
Ok, i've been analyzing the testapp (not executed it already) and AFAIK the code i've readed the plugin is only being used and initialized from the same page, so you can't keep it running in background. In my app, as i've said the code is being initialized in initialView, so it's started when app starts. Then after register the device, the two events (foreground and background triggers) keeps running in that view that it's hidden all the time while the app is running. I bet that this is where the plugin fails, but may be i'm wrong... anyway, there is no way to test this with your testapp cause you can't hide the plugin webView and continue using the app while the events to receive the notifications are running in background.

**Comment by fidoboy** [comment] 2015-01-21 15:17
I should add that in 'real life' my approach is the only practical way to use this plugin; in other case, you'll need to repeat the code and initialize the plugin for each webView in app, in order to have it running always into the active webView, and this has no sense. The main advantage of steroids is always the use of multiple and independent webViews, but also you always need a background view to centralize some common tasks, like push notifications for example.

**Comment by pre** [comment] 2015-01-22 09:36
This plugin is based on the Push Plugin which is originally not aware of multiple webviews. 

Although there are fixes for our MPA view stack, you really should not use the plugin from several WebViews at once. 

The unreleased API for `supersonic.push()` creates a communications channel for you so that the plugin can be initialized in one webview and other views can access push notifications without accessing the plugin directly. This API will change in the future, but you'll get the idea, see: https://github.com/AppGyver/supersonic/blob/master/src/supersonic/core/device/push.coffee

**Comment by fidoboy** [comment] 2015-01-22 13:25
It seems that I've explained myself really bad.... That's exactly what I'm doing and it doesn't works. I'm calling/using the plugin from a single webView; but problem is that this webView is not active/visible. My theory is that this is what is causing the problem and the plugin is not triggering the event in my webView cause it's not visible/active in the app.

**Comment by fidoboy** [comment] 2015-01-22 13:29
To summarize, the only difference that I can notice from testapp and my app is that my app is calling/using the plugin from a hidden webView and I can't get it working. The foreground event is never being triggered in my app

**Comment by harsaharsa** [comment] 2015-01-28 09:01
Closing as duplicate of https://github.com/AppGyver/PushNotifications/issues/3

**Closed by harsaharsa** 2015-01-28 09:01 UTC
