### ISSUE TITLE
Help on using AppGyver Push Plugin with Parse.com push backend.

### ISSUE THREAD

**Issue by kkgelu** [AppGyver/PushNotifications#26] opened 2015-06-07 22:40 UTC
By far, me and my team are very excited about AppGyver/Supersonic! Well done!

Now we are at the chapter of Push Notifications. Our problem now is incoming push is not displayed over the status bar, basically nothing happens. I have tried Android so far, the push message is received (will elaborate soon), but not displayed when app is foreground, in background or not running at all.

A check list here, I have
- setup an app at Google, got the Sender ID and API Key
- built an app specific scanner with Push Notification Plugin checked on build service (also tried adhoc and Google Play builds)
- Plugin successfully retrieved a token on Android device (4.4.4 Sony Xperia M2)
- the token is saved to Parse backend, I mimicked the Parse installation (Parse does have REST API for this process https://www.parse.com/docs/rest/guide#push-notifications)

I then used Parse.com to send push messages to this installation/token, from Parse's point of view, it's a success! The message is sent in JSON format:

{"message":"made in heaven?","msgcnt":"1"}

For debugging convenience, I let the app running in foreground, attached the AppGyver Connect DEBUG to see the push message, this is what I got in debugger:

![screen shot 2015-06-07 at 23 48 48](https://cloud.githubusercontent.com/assets/11604017/8026402/587eea8a-0d74-11e5-9225-d808c6691c2a.png)

My alert code can display "made in heaven?" message, meaning it came all the way through Parse.com Push backend -> GCM -> Device. But really, nothing displayed over the status bar.

I thought this might be incompatibility issues between what's sent out by Parse.com and what the plugin is expecting. Because from the screenshot, everything falls into the payload.data object. You documentation says:
>
 The Android implementation in this plugin, for example, assumes the incoming message will contain a 'message' and a 'msgcnt' node. 

Or I am completely missing something here. Do I need to write code to actually display the notification?

Feeling I am pretty close there. Please offer some thoughts here, I believe Supersonic and Parse should really be made in heaven.

# Kiitos

(Similar issue found on AppGyver forum: http://community.appgyver.com/t/steroids2-push-parse/2768)

**Comment by wzfcooler** [comment] 2015-06-07 22:56
+1 can't wait to see how to solve this problem.

**Comment by kkgelu** [comment] 2015-06-07 23:04
I have also tried this plugin:  https://github.com/benjie/phonegap-parse-plugin

On Android, Push works when app is in foreground or in background, but not when the app is completely not running. I understood this is because the plugin should be initialised in Application class instead of an activity: https://github.com/avivais/phonegap-parse-plugin/issues/54

I think it means I need to provide this:
```    
public class App extends Application {
          @Override 
        public void onCreate() {
        super.onCreate();
        ParsePlugin.initializeParseWithApplication(this);
    }
}
```

And configure that in AndroidManifest.xml.

If I understood your current architecture, customising App class and AndroidManifest.xml is not supported, or won't be supported.

So my hope is still on tying together AppGyver Push plugin and push Parse.com backend.

(Plus this phonegap-parse-plugin has problem of not forwarding beyond the splashing screen after clicking messages on push notification hub).

**Comment by harsaharsa** [comment] 2015-06-08 13:21
We'll look into this – I think the reason is that the plugin currently looks for the `message` key in the payload root, and if it doesn't find it, it doesn't create the notification in the notification center.

Solution is to code support for the specific case of `data.message`, or add a config option so the user can specify any custom path for the message key.

**Comment by kkgelu** [comment] 2015-06-08 13:48
@harsaharsa  thank you very much for the reply!

Could you clarify a bit? When you say solution, did you mean a solution that you are going do to in the plugin, we (as plugin users) just need to configure the plugin with something like MSG_CONTENT_PATH and MSG_CNT_PATH ?

Or something I can do it myself now?

**Comment by harsaharsa** [comment] 2015-06-09 13:52
The former – this functionality needs to be coded into the plugin. PRs are welcome before we get to this on our backlog, it should be relatively easy to parameterize the path!

**Comment by Blechfalke** [comment] 2015-06-10 11:35
+1

**Comment by kkgelu** [comment] 2015-06-10 18:51
@harsaharsa  many thanks! I will try to fork it and implement the customisable message path in payload at later time - if it still sits in your backlog by then ^^.

Just a note here, by default, messages Parse.com backend sends for Android end up on client side in this format:
                `payload.data.alert = "this is usually the message content"`


On iOS, this plugin works like a charm with Parse push backend.

**Comment by Blechfalke** [comment] 2015-06-11 08:38
I forked and modified the function, which was creating the notification. 
Now it creates a notification from parse.com pushes too. 

Some notes:
- The title defaults to the Appname 
- I have only tested it with plain text messages, not JSON.

Feel free to implement it:
https://github.com/Blechfalke/PushNotifications.git

**Comment by kkgelu** [comment] 2015-06-11 21:31
@Blechfalke thank you! I confirm your plugin works with Parse.com on Android! Awesome.

**Comment by harsaharsa** [comment] 2015-06-12 09:23
Just to update, since this use case is covered with the fork, this is not super high on our backlog. If someone wants to make a PR that parametrizes the message root key, we're happy to review and merge it though!

**Comment by harsaharsa** [comment] 2015-07-13 11:08
Closing this as duplicate of #25

**Closed by harsaharsa** 2015-07-13 11:08 UTC

**Comment by s-stude** [comment] 2015-09-06 10:36
The fork from @Blechfalke (https://github.com/Blechfalke/PushNotifications.git) works great! :+1: :tada:
