### ISSUE TITLE
"App not installed" on Android w/ notification plugin

### ISSUE THREAD

**Issue by ezramorse** [AppGyver/PushNotifications#33] opened 2015-11-05 20:13 UTC
Nevermind - The issue was that the app will not install if appgyver scanner is installed already on our device.

**Comment by ezramorse** [comment] 2015-11-06 13:36
While this is solved for me, I surely hope that if someone has another appgyver based app on their system, android wont prevent the installation of news one (as the scanner seems to do).

**Comment by pre** [comment] 2015-11-11 15:05
This will be fixed at some point. For now there can be only one AppGyver build installed with the push notification plugin.

**Comment by harsaharsa** [comment] 2016-03-18 12:36
@ezramorse this has now been fixed, and new builds will set the push notification plugin package identifier (which was the cause for the install error) correctly.

**Closed by harsaharsa** 2016-03-18 12:36 UTC
